// <auto-generated />
using System;
using DaemonsMCP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaemonsMCP.Infrastructure.Migrations
{
    [DbContext(typeof(DaemonsMcpDbContext))]
    [Migration("20260101224145_AddModelAndProperties")]
    partial class AddModelAndProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.AccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevokedChain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IssuedTo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("unknown");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("Used")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsedUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("UsedUrlNextToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Expires");

                    b.HasIndex("ParentId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("Used");

                    b.HasIndex("UsedBy");

                    b.HasIndex("UsedUrl");

                    b.HasIndex("Expires", "UsedUrl");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.FileSystemNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "ParentId");

                    b.HasIndex("ProjectId", "RelativePath")
                        .IsUnique();

                    b.ToTable("FileSystemNodes");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.GitBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GitRepositoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrentBranch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRemote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTracking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastCommitAuthor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastCommitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastCommitMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LastCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TrackingBranchName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("GitRepositoryId")
                        .HasDatabaseName("IX_GitBranches_GitRepositoryId");

                    b.HasIndex("GitRepositoryId", "FullName")
                        .IsUnique()
                        .HasDatabaseName("UQ_GitBranches_UniqueName");

                    b.HasIndex("GitRepositoryId", "IsCurrentBranch")
                        .HasDatabaseName("IX_GitBranches_IsCurrentBranch")
                        .HasFilter("[IsCurrentBranch] = 1");

                    b.ToTable("GitBranches", (string)null);
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.GitRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentBranchName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDirty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LastSyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ModifiedFileCount")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RemoteName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("origin");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("UntrackedFileCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UserCredentialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_GitRepositories_ProjectId");

                    b.HasIndex("UserCredentialId")
                        .HasDatabaseName("IX_GitRepositories_UserCredentialId");

                    b.HasIndex("ProjectId", "LocalPath")
                        .IsUnique()
                        .HasDatabaseName("UQ_GitRepositories_ProjectPath");

                    b.ToTable("GitRepositories", (string)null);
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Identifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Identifiers");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.IdentifierType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IdentifierTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "namespace"
                        },
                        new
                        {
                            Id = 2,
                            Name = "interface"
                        },
                        new
                        {
                            Id = 3,
                            Name = "class"
                        },
                        new
                        {
                            Id = 4,
                            Name = "method"
                        },
                        new
                        {
                            Id = 5,
                            Name = "property"
                        },
                        new
                        {
                            Id = 6,
                            Name = "field"
                        },
                        new
                        {
                            Id = 7,
                            Name = "event"
                        },
                        new
                        {
                            Id = 8,
                            Name = "methodParameter"
                        });
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.IndexQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FileSystemNodeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileSystemNodeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("IndexQueues");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.InvitationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsedByUserId");

                    b.ToTable("InvitationTokens", (string)null);
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemTypeId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceFileSystemId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceObjectHierarchyId")
                        .HasColumnType("int");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Completed");

                    b.HasIndex("Created");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("ItemTypeId1");

                    b.HasIndex("ParentId");

                    b.HasIndex("ReferenceFileSystemId");

                    b.HasIndex("ReferenceObjectHierarchyId");

                    b.HasIndex("StatusTypeId");

                    b.HasIndex("ItemTypeId", "StatusTypeId");

                    b.HasIndex("ParentId", "Rank");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Living documentation for the Daemons3MCP tool. This documentation is stored as hierarchical nodes and can be extended through the nodes interface. The system provides tools for file management, code indexing, and hierarchical note/task organization.",
                            ItemTypeId = 6,
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Daemons3MCP Documentation",
                            Rank = 1,
                            StatusTypeId = 12
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Root container for all todo lists. Todo lists are created as children of this node. Use make-todo-list to create new lists, and get-next-todo to retrieve the next actionable item.",
                            ItemTypeId = 5,
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Todo Root",
                            Rank = 2,
                            StatusTypeId = 11
                        });
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentId", "Rank");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Reserved null type - default unset value",
                            Name = "None",
                            Rank = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Internal root - high-level grouping for type categories",
                            Name = "Categories",
                            Rank = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Parent container for all item type definitions",
                            Name = "ItemTypes",
                            ParentId = 2,
                            Rank = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Parent container for all status type definitions",
                            Name = "StatusTypes",
                            ParentId = 2,
                            Rank = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "A task or action item to be completed",
                            Name = "Todo",
                            ParentId = 3,
                            Rank = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Documentation or informational content",
                            Name = "Readme",
                            ParentId = 3,
                            Rank = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "General note or observation",
                            Name = "Note",
                            ParentId = 3,
                            Rank = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Item has not been started yet",
                            Name = "Not Started",
                            ParentId = 4,
                            Rank = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Item is currently being worked on",
                            Name = "In Progress",
                            ParentId = 4,
                            Rank = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Item is finished",
                            Name = "Complete",
                            ParentId = 4,
                            Rank = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Item is paused or waiting",
                            Name = "On Hold",
                            ParentId = 4,
                            Rank = 4
                        },
                        new
                        {
                            Id = 14,
                            Description = "Item was cancelled and will not be completed",
                            Name = "Cancelled",
                            ParentId = 4,
                            Rank = 5
                        });
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ModelTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ModelTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "ParentId", "Rank");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ModelProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PropertyValueTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("PropertyKey");

                    b.HasIndex("PropertyValueTypeId");

                    b.HasIndex("ModelId", "PropertyKey")
                        .IsUnique();

                    b.ToTable("ModelProperties");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ModelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<int?>("EditorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsReadonly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OwnerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryTypeId");

                    b.HasIndex("EditorTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerTypeId");

                    b.HasIndex("OwnerTypeId", "TypeRank");

                    b.ToTable("ModelTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Base root type model",
                            IconName = "pi-cog",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "Root Internal Owner Type Model",
                            TypeRank = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryTypeId = 2,
                            Description = "Adds node for categories dimension",
                            EditorTypeId = 2,
                            IconName = "pi-folder",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "Categories",
                            OwnerTypeId = 1,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryTypeId = 2,
                            Description = "Adds node for editor types dimension",
                            EditorTypeId = 2,
                            IconName = "pi-pencil",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "Editor Types",
                            OwnerTypeId = 1,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryTypeId = 3,
                            Description = "editor is hidden",
                            EditorTypeId = 10,
                            IconName = "pi-eye-slash",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "Hidden",
                            OwnerTypeId = 3,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryTypeId = 3,
                            Description = "boolean editor",
                            EditorTypeId = 11,
                            IconName = "pi-check",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Boolean",
                            OwnerTypeId = 3,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryTypeId = 3,
                            Description = "integer editor",
                            EditorTypeId = 12,
                            IconName = "pi-pencil",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Integer",
                            OwnerTypeId = 3,
                            TypeRank = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryTypeId = 3,
                            Description = "string editor",
                            EditorTypeId = 13,
                            IconName = "pi-pencil",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "String",
                            OwnerTypeId = 3,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 14,
                            CategoryTypeId = 3,
                            Description = "filename editor",
                            EditorTypeId = 14,
                            IconName = "pi-file",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Filename",
                            OwnerTypeId = 3,
                            TypeRank = 5
                        },
                        new
                        {
                            Id = 15,
                            CategoryTypeId = 3,
                            Description = "date editor",
                            EditorTypeId = 15,
                            IconName = "pi-calendar",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Date",
                            OwnerTypeId = 3,
                            TypeRank = 6
                        },
                        new
                        {
                            Id = 16,
                            CategoryTypeId = 3,
                            Description = "time editor",
                            EditorTypeId = 16,
                            IconName = "pi-clock",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Time",
                            OwnerTypeId = 3,
                            TypeRank = 7
                        },
                        new
                        {
                            Id = 17,
                            CategoryTypeId = 3,
                            Description = "decimal editor",
                            EditorTypeId = 17,
                            IconName = "pi-dollar",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Decimal",
                            OwnerTypeId = 3,
                            TypeRank = 8
                        },
                        new
                        {
                            Id = 18,
                            CategoryTypeId = 3,
                            Description = "password editor",
                            EditorTypeId = 18,
                            IconName = "pi-lock",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Password",
                            OwnerTypeId = 3,
                            TypeRank = 9
                        },
                        new
                        {
                            Id = 19,
                            CategoryTypeId = 3,
                            Description = "lookup editor",
                            EditorTypeId = 19,
                            IconName = "pi-search",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Lookup",
                            OwnerTypeId = 3,
                            TypeRank = 10
                        },
                        new
                        {
                            Id = 50,
                            CategoryTypeId = 3,
                            Description = "HTTP method types editor",
                            IconName = "pi-pencil",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "HTTP Method Types",
                            OwnerTypeId = 2,
                            TypeRank = 11
                        },
                        new
                        {
                            Id = 52,
                            CategoryTypeId = 3,
                            Description = "HTTP GET method",
                            IconName = "pi-eye",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "GET",
                            OwnerTypeId = 50,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 53,
                            CategoryTypeId = 3,
                            Description = "HTTP POST method",
                            IconName = "pi-pencil",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "POST",
                            OwnerTypeId = 50,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 54,
                            CategoryTypeId = 3,
                            Description = "HTTP PUT method",
                            IconName = "pi-pencil",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "PUT",
                            OwnerTypeId = 50,
                            TypeRank = 3
                        },
                        new
                        {
                            Id = 55,
                            CategoryTypeId = 3,
                            Description = "HTTP DELETE method",
                            IconName = "pi-delete-left",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "DELETE",
                            OwnerTypeId = 50,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 56,
                            CategoryTypeId = 3,
                            Description = "HTTP PATCH method",
                            EditorTypeId = 13,
                            IconName = "pi-pencil",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "PATCH",
                            OwnerTypeId = 50,
                            TypeRank = 5
                        },
                        new
                        {
                            Id = 60,
                            CategoryTypeId = 2,
                            Description = "Accessibility types list",
                            EditorTypeId = 2,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "C# Accessibility Types",
                            OwnerTypeId = 2,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 62,
                            CategoryTypeId = 3,
                            Description = "public accessibility",
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "public",
                            OwnerTypeId = 60,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 64,
                            CategoryTypeId = 3,
                            Description = "private accessibility",
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "private",
                            OwnerTypeId = 60,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 66,
                            CategoryTypeId = 3,
                            Description = "protected accessibility",
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "protected",
                            OwnerTypeId = 60,
                            TypeRank = 3
                        },
                        new
                        {
                            Id = 68,
                            CategoryTypeId = 3,
                            Description = "internal accessibility",
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "internal",
                            OwnerTypeId = 60,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 100,
                            CategoryTypeId = 2,
                            Description = "Sql data types list",
                            EditorTypeId = 2,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "Sql Types",
                            OwnerTypeId = 3,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 101,
                            CategoryTypeId = 3,
                            Description = "SQL bit type",
                            EditorTypeId = 11,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "bit",
                            OwnerTypeId = 100,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 102,
                            CategoryTypeId = 3,
                            Description = "SQL Small Integer type",
                            EditorTypeId = 12,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "smallint",
                            OwnerTypeId = 100,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 103,
                            CategoryTypeId = 3,
                            Description = "SQL Integer type",
                            EditorTypeId = 12,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "int",
                            OwnerTypeId = 100,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 104,
                            CategoryTypeId = 3,
                            Description = "SQL bigint type",
                            EditorTypeId = 12,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "bigint",
                            OwnerTypeId = 100,
                            TypeRank = 8
                        },
                        new
                        {
                            Id = 106,
                            CategoryTypeId = 3,
                            Description = "SQL uniqueidentifier type",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "uniqueidentifier",
                            OwnerTypeId = 100,
                            TypeRank = 9
                        },
                        new
                        {
                            Id = 108,
                            CategoryTypeId = 3,
                            Description = "SQL Variable Character type",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "varchar",
                            OwnerTypeId = 100,
                            TypeRank = 3
                        },
                        new
                        {
                            Id = 110,
                            CategoryTypeId = 3,
                            Description = "SQL National Variable Character type",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "nvarchar",
                            OwnerTypeId = 100,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 112,
                            CategoryTypeId = 3,
                            Description = "SQL Decimal type",
                            EditorTypeId = 17,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "decimal",
                            OwnerTypeId = 100,
                            TypeRank = 5
                        },
                        new
                        {
                            Id = 114,
                            CategoryTypeId = 3,
                            Description = "SQL DateTime type",
                            EditorTypeId = 15,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "datetime",
                            OwnerTypeId = 100,
                            TypeRank = 6
                        },
                        new
                        {
                            Id = 118,
                            CategoryTypeId = 3,
                            Description = "SQL date type",
                            EditorTypeId = 15,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "date",
                            OwnerTypeId = 100,
                            TypeRank = 10
                        },
                        new
                        {
                            Id = 120,
                            CategoryTypeId = 3,
                            Description = "SQL time type",
                            EditorTypeId = 16,
                            IconName = "",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "time",
                            OwnerTypeId = 100,
                            TypeRank = 11
                        },
                        new
                        {
                            Id = 150,
                            CategoryTypeId = 2,
                            Description = "C# Type Lookups",
                            EditorTypeId = 2,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "C# Types",
                            OwnerTypeId = 2,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 152,
                            CategoryTypeId = 3,
                            Description = "C# class model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "class",
                            OwnerTypeId = 150,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 154,
                            CategoryTypeId = 3,
                            Description = "C# record model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "record",
                            OwnerTypeId = 150,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 156,
                            CategoryTypeId = 3,
                            Description = "C# struct model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "struct",
                            OwnerTypeId = 150,
                            TypeRank = 3
                        },
                        new
                        {
                            Id = 158,
                            CategoryTypeId = 3,
                            Description = "C# string model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "string",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 160,
                            CategoryTypeId = 3,
                            Description = "C# bool model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "bool",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 162,
                            CategoryTypeId = 3,
                            Description = "C# char model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "char",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 164,
                            CategoryTypeId = 3,
                            Description = "C# int model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "int",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 166,
                            CategoryTypeId = 3,
                            Description = "C# long model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "long",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 168,
                            CategoryTypeId = 3,
                            Description = "C# short model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "short",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 170,
                            CategoryTypeId = 3,
                            Description = "C# decimal model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "decimal",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 172,
                            CategoryTypeId = 3,
                            Description = "C# double model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "double",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 174,
                            CategoryTypeId = 3,
                            Description = "C# float model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "float",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 176,
                            CategoryTypeId = 3,
                            Description = "C# byte model",
                            EditorTypeId = 13,
                            IconName = "",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "byte",
                            OwnerTypeId = 150,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 200,
                            CategoryTypeId = 2,
                            Description = "",
                            EditorTypeId = 2,
                            IconName = "pi-microchip",
                            IsReadonly = true,
                            IsVisible = false,
                            Name = "Project Templates",
                            OwnerTypeId = 2,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 210,
                            CategoryTypeId = 3,
                            Description = "database model",
                            EditorTypeId = 13,
                            IconName = "pi-database",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Database",
                            OwnerTypeId = 200,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 220,
                            CategoryTypeId = 200,
                            Description = "database tables folder",
                            EditorTypeId = 13,
                            IconName = "pi-folder",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "Tables",
                            OwnerTypeId = 210,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 222,
                            CategoryTypeId = 200,
                            Description = "database table",
                            EditorTypeId = 13,
                            IconName = "pi-table",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Table",
                            OwnerTypeId = 220,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 226,
                            CategoryTypeId = 200,
                            Description = "database table column model",
                            EditorTypeId = 13,
                            IconName = "pi-stop",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "TableColumn",
                            OwnerTypeId = 222,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 230,
                            CategoryTypeId = 200,
                            Description = "database views folder",
                            EditorTypeId = 13,
                            IconName = "pi-folder",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "Views",
                            OwnerTypeId = 210,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 232,
                            CategoryTypeId = 200,
                            Description = "database table",
                            EditorTypeId = 13,
                            IconName = "pi-table",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Table",
                            OwnerTypeId = 230,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 236,
                            CategoryTypeId = 200,
                            Description = "database table column model",
                            EditorTypeId = 13,
                            IconName = "pi-stop",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "TableColumn",
                            OwnerTypeId = 232,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 240,
                            CategoryTypeId = 200,
                            Description = "database functions folder",
                            EditorTypeId = 13,
                            IconName = "pi-folder",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "Functions",
                            OwnerTypeId = 210,
                            TypeRank = 3
                        },
                        new
                        {
                            Id = 242,
                            CategoryTypeId = 200,
                            Description = "database function",
                            EditorTypeId = 13,
                            IconName = "pi-tablet",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Function",
                            OwnerTypeId = 240,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 246,
                            CategoryTypeId = 200,
                            Description = "database function column model",
                            EditorTypeId = 13,
                            IconName = "pi-stop",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "FunctionColumn",
                            OwnerTypeId = 242,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 250,
                            CategoryTypeId = 200,
                            Description = "database procedures folder",
                            EditorTypeId = 13,
                            IconName = "pi-folder",
                            IsReadonly = true,
                            IsVisible = true,
                            Name = "Procedures",
                            OwnerTypeId = 210,
                            TypeRank = 4
                        },
                        new
                        {
                            Id = 252,
                            CategoryTypeId = 200,
                            Description = "database procedure",
                            EditorTypeId = 13,
                            IconName = "pi-microchip",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Procedure",
                            OwnerTypeId = 250,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 256,
                            CategoryTypeId = 200,
                            Description = "database procedure parameter model",
                            EditorTypeId = 13,
                            IconName = "pi-stop",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Parameter",
                            OwnerTypeId = 252,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 300,
                            CategoryTypeId = 3,
                            Description = "API model",
                            EditorTypeId = 13,
                            IconName = "pi-warehouse",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Api",
                            OwnerTypeId = 200,
                            TypeRank = 2
                        },
                        new
                        {
                            Id = 310,
                            CategoryTypeId = 3,
                            Description = "API controller model",
                            EditorTypeId = 13,
                            IconName = "pi-microchip",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Controller",
                            OwnerTypeId = 300,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 312,
                            CategoryTypeId = 3,
                            Description = "API controller property model",
                            EditorTypeId = 13,
                            IconName = "pi-tag",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Property",
                            OwnerTypeId = 310,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 314,
                            CategoryTypeId = 3,
                            Description = "API controller method model",
                            EditorTypeId = 13,
                            IconName = "pi-stop",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Method",
                            OwnerTypeId = 312,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 316,
                            CategoryTypeId = 3,
                            Description = "API controller method parameter model",
                            EditorTypeId = 13,
                            IconName = "pi-tablet",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Parameter",
                            OwnerTypeId = 314,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 320,
                            CategoryTypeId = 3,
                            Description = "API class model",
                            EditorTypeId = 13,
                            IconName = "pi-microchip",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Class",
                            OwnerTypeId = 300,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 322,
                            CategoryTypeId = 3,
                            Description = "API class property model",
                            EditorTypeId = 13,
                            IconName = "pi-tag",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Property",
                            OwnerTypeId = 320,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 324,
                            CategoryTypeId = 3,
                            Description = "API class method model",
                            EditorTypeId = 13,
                            IconName = "pi-stop",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Method",
                            OwnerTypeId = 322,
                            TypeRank = 1
                        },
                        new
                        {
                            Id = 326,
                            CategoryTypeId = 3,
                            Description = "API class method parameter model",
                            EditorTypeId = 13,
                            IconName = "pi-tablet",
                            IsReadonly = false,
                            IsVisible = true,
                            Name = "Parameter",
                            OwnerTypeId = 324,
                            TypeRank = 1
                        });
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ObjectHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FileSystemNodeId")
                        .HasColumnType("int");

                    b.Property<int>("IdentifierId")
                        .HasColumnType("int");

                    b.Property<int>("IdentifierTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineEnd")
                        .HasColumnType("int");

                    b.Property<int>("LineStart")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileSystemNodeId");

                    b.HasIndex("IdentifierId");

                    b.HasIndex("IdentifierTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "ParentId");

                    b.ToTable("ObjectHierarchies");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comma-separated list of folder names to exclude from sync",
                            Key = "FileSystem.BlockedFolders",
                            ModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "bin,obj,node_modules,.git,.vs,.vscode,packages,Debug,Release,TestResults,.idea"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comma-separated list of file extensions to exclude from sync",
                            Key = "FileSystem.BlockedExtensions",
                            ModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ".dll,.exe,.pdb,.cache,.suo,.user,.tmp,.temp,.log,.bak"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "If set, only these extensions are synced (leave empty to allow all non-blocked)",
                            Key = "FileSystem.AllowedExtensions",
                            ModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ".cs,.csproj,.sln,.json,.xml,.md,.txt,.config,.yml,.yaml"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comma-separated list of specific filenames to exclude",
                            Key = "FileSystem.BlockedFiles",
                            ModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ".DS_Store,Thumbs.db,desktop.ini"
                        });
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GitHubId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GitHubId")
                        .IsUnique()
                        .HasFilter("[GitHubId] IS NOT NULL");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CredentialType")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedSecret")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptedUsername")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.AccessToken", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.AccessToken", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.FileSystemNode", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.FileSystemNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaemonsMCP.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.GitBranch", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.GitRepository", "GitRepository")
                        .WithMany("Branches")
                        .HasForeignKey("GitRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitRepository");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.GitRepository", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.UserCredential", "UserCredential")
                        .WithMany("GitRepositories")
                        .HasForeignKey("UserCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("UserCredential");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.IndexQueue", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.FileSystemNode", "FileSystemNode")
                        .WithMany()
                        .HasForeignKey("FileSystemNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FileSystemNode");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.InvitationToken", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.User", "UsedBy")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UsedBy");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Item", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.ItemType", null)
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId1");

                    b.HasOne("DaemonsMCP.Domain.Entities.Item", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaemonsMCP.Domain.Entities.FileSystemNode", "ReferenceFileSystem")
                        .WithMany()
                        .HasForeignKey("ReferenceFileSystemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaemonsMCP.Domain.Entities.ObjectHierarchy", "ReferenceObjectHierarchy")
                        .WithMany()
                        .HasForeignKey("ReferenceObjectHierarchyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaemonsMCP.Domain.Entities.ItemType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Parent");

                    b.Navigation("ReferenceFileSystem");

                    b.Navigation("ReferenceObjectHierarchy");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ItemType", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.ItemType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Model", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.ModelType", "ModelType")
                        .WithMany()
                        .HasForeignKey("ModelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.Model", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaemonsMCP.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelType");

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ModelProperty", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.Model", "Model")
                        .WithMany("Properties")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.ModelType", "PropertyModelType")
                        .WithMany()
                        .HasForeignKey("PropertyValueTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Model");

                    b.Navigation("PropertyModelType");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ModelType", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.ModelType", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaemonsMCP.Domain.Entities.ModelType", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaemonsMCP.Domain.Entities.ModelType", "Owner")
                        .WithMany("Children")
                        .HasForeignKey("OwnerTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Editor");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ObjectHierarchy", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.FileSystemNode", "FileSystemNode")
                        .WithMany()
                        .HasForeignKey("FileSystemNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.Identifier", "Identifier")
                        .WithMany()
                        .HasForeignKey("IdentifierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.IdentifierType", "IdentifierType")
                        .WithMany()
                        .HasForeignKey("IdentifierTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DaemonsMCP.Domain.Entities.ObjectHierarchy", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DaemonsMCP.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FileSystemNode");

                    b.Navigation("Identifier");

                    b.Navigation("IdentifierType");

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.UserCredential", b =>
                {
                    b.HasOne("DaemonsMCP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.AccessToken", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.FileSystemNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.GitRepository", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Item", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ItemType", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.Model", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ModelType", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.ObjectHierarchy", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DaemonsMCP.Domain.Entities.UserCredential", b =>
                {
                    b.Navigation("GitRepositories");
                });
#pragma warning restore 612, 618
        }
    }
}
